/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mpmgc.formula1.app;

public class ConsoleApp {
    public static void main(String[] args) {
        System.out.println("funziona");
    }
}
